name: .

params:
  min_epochs: 15
  max_epochs: 100
  accumulate_grad_batches: 1
  log_every_n_steps: 20
  num_sanity_val_steps: 1
  devices: 1
  accelerator: auto
  num_nodes: 1
  deterministic: True
  benchmark: False
  profiler: False
