name: CVpipeline-smp
channels:
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - annotated-doc=0.0.4
  - anyio=4.12.1
  - aom=3.9.1
  - backports.zstd=1.3.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - cfgv=3.5.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - cpython=3.13.12
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - dav1d=1.2.1
  - distlib=0.4.0
  - efficientnet-pytorch=0.7.1
  - exceptiongroup=1.3.1
  - filelock=3.20.3
  - fmt=12.1.0
  - fsspec=2026.2.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h11=0.16.0
  - h2=4.3.0
  - hf-xet=1.2.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=1.4.1
  - hyperframe=6.1.0
  - icu=78.2
  - identify=2.6.16
  - idna=3.11
  - iniconfig=2.3.0
  - jinja2=3.1.6
  - lcms2=2.18
  - ld_impl_linux-64=2.45.1
  - lerc=4.0.0
  - libabseil=20260107.0
  - libavif16=1.3.0
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libde265=1.0.15
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libheif=1.19.7
  - libhwloc=2.12.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libmpdec=4.0.0
  - libnpp=12.2.5.30
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libopenblas=0.3.30
  - libpng=1.6.55
  - libprotobuf=6.33.5
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libtorch=2.10.0
  - libuuid=2.41.3
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - lightning-utilities=0.15.2
  - llvm-openmp=21.1.8
  - markupsafe=3.0.3
  - mkl=2025.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munch=4.0.0
  - ncurses=6.5
  - networkx=3.6.1
  - nodeenv=1.10.0
  - numpy=2.4.2
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openjpeg=2.5.4
  - openssl=3.6.1
  - optree=0.18.0
  - packaging=26.0
  - pillow=12.1.1
  - pip=26.0.1
  - platformdirs=4.5.1
  - pluggy=1.6.0
  - pre-commit=4.5.1
  - pretrainedmodels=0.7.4
  - pthread-stubs=0.4
  - pybind11=3.0.1
  - pybind11-abi=11
  - pybind11-global=3.0.1
  - pycparser=2.22
  - pygments=2.19.2
  - pysocks=1.7.1
  - pytest=9.0.2
  - python=3.13.12
  - python-gil=3.13.12
  - python_abi=3.13
  - pytorch=2.10.0
  - pytorch-cuda=12.4
  - pytorch-lightning=2.6.1
  - pyyaml=6.0.3
  - rav1e=0.7.1
  - readline=8.3
  - requests=2.32.5
  - safetensors=0.7.0
  - scipy=1.17.0
  - segmentation-models-pytorch=0.5.0
  - setuptools=82.0.0
  - shellingham=1.5.4
  - six=1.17.0
  - sleef=3.9.0
  - sniffio=1.3.1
  - svt-av1=4.0.0
  - sympy=1.14.0
  - tbb=2022.3.0
  - timm=1.0.24
  - tk=8.6.13
  - tomli=2.4.0
  - torchmetrics=1.8.2
  - torchvision=0.25.0
  - torchvision-extra-decoders=0.0.2
  - tqdm=4.67.3
  - typer-slim=0.21.2
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - ukkonen=1.1.0
  - urllib3=2.6.3
  - virtualenv=20.36.1
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zlib-ng=2.3.3
  - zstd=1.5.7
