name: CVpipeline-smp
channels:
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.3
  - aiosignal=1.4.0
  - albucore=0.0.24
  - albumentations=2.0.8
  - alsa-lib=1.2.15.3
  - annotated-doc=0.0.4
  - annotated-types=0.7.0
  - antlr-python-runtime=4.9.3
  - anyio=4.12.1
  - aom=3.9.1
  - attr=2.5.2
  - attrs=25.4.0
  - backports.zstd=1.3.0
  - blas=2.108
  - blas-devel=3.9.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cachetools=6.2.6
  - cairo=1.18.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - cfgv=3.5.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - cpython=3.11.14
  - cryptography=46.0.5
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - cyrus-sasl=2.1.28
  - databricks-sdk=0.86.0
  - dav1d=1.2.1
  - dbus=1.16.2
  - deprecated=1.3.1
  - distlib=0.4.0
  - dnspython=2.8.0
  - double-conversion=3.4.0
  - efficientnet-pytorch=0.7.1
  - email-validator=2.3.0
  - email_validator=2.3.0
  - eval-type-backport=0.3.1
  - eval_type_backport=0.3.1
  - exceptiongroup=1.3.1
  - fastapi=0.128.7
  - fastapi-cli=0.0.20
  - fastapi-core=0.128.7
  - ffmpeg=8.0.1
  - filelock=3.20.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.2.2
  - freetype=2.14.1
  - fribidi=1.0.16
  - frozenlist=1.7.0
  - fsspec=2026.2.0
  - gdk-pixbuf=2.44.5
  - gitdb=4.0.12
  - gitpython=3.1.46
  - glslang=16.2.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-auth=2.48.0
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.3.2
  - hdf5=1.14.6
  - hf-xet=1.2.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - huggingface_hub=1.4.1
  - hydra-core=1.3.2
  - hyperframe=6.1.0
  - icu=78.2
  - identify=2.6.16
  - idna=3.11
  - imath=3.2.2
  - importlib-metadata=8.7.0
  - iniconfig=2.3.0
  - intel-gmmlib=22.9.0
  - intel-media-driver=25.3.4
  - jasper=4.2.8
  - jinja2=3.1.6
  - joblib=1.5.3
  - keyutils=1.6.3
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.18
  - ld_impl_linux-64=2.45.1
  - lerc=4.0.0
  - level-zero=1.28.0
  - libabseil=20250512.1
  - libaec=1.1.5
  - libass=0.17.4
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.77
  - libcblas=3.9.0
  - libclang-cpp21.1=21.1.8
  - libclang13=21.1.8
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcups=2.3.3
  - libcurand=10.3.5.147
  - libcurl=8.18.0
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libflac=1.5.0
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.2
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm21=21.1.8
  - liblzma=5.8.2
  - libnghttp2=1.67.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libogg=1.3.5
  - libopencv=4.13.0
  - libopengl=1.7.0
  - libopenvino=2025.4.1
  - libopenvino-auto-batch-plugin=2025.4.1
  - libopenvino-auto-plugin=2025.4.1
  - libopenvino-hetero-plugin=2025.4.1
  - libopenvino-intel-cpu-plugin=2025.4.1
  - libopenvino-intel-gpu-plugin=2025.4.1
  - libopenvino-intel-npu-plugin=2025.4.1
  - libopenvino-ir-frontend=2025.4.1
  - libopenvino-onnx-frontend=2025.4.1
  - libopenvino-paddle-frontend=2025.4.1
  - libopenvino-pytorch-frontend=2025.4.1
  - libopenvino-tensorflow-frontend=2025.4.1
  - libopenvino-tensorflow-lite-frontend=2025.4.1
  - libopus=1.6.1
  - libpciaccess=0.18
  - libpng=1.6.55
  - libpq=18.1
  - libprotobuf=6.31.1
  - librsvg=2.60.0
  - libsndfile=1.2.2
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=259.1
  - libtiff=4.7.1
  - libudev1=259.1
  - libunwind=1.8.3
  - liburing=2.13
  - libusb=1.0.29
  - libuuid=2.41.3
  - libuv=1.51.0
  - libva=2.23.0
  - libvorbis=1.3.7
  - libvpl=2.15.0
  - libvpx=1.15.2
  - libvulkan-loader=1.4.341.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - lightning-utilities=0.15.2
  - llvm-openmp=15.0.7
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - mdurl=0.1.2
  - mkl=2020.4
  - mkl-devel=2020.4
  - mkl-include=2020.4
  - mlflow-skinny=3.9.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - multidict=6.7.0
  - munch=4.0.0
  - ncurses=6.5
  - networkx=3.6.1
  - nodeenv=1.10.0
  - numpy=2.4.2
  - ocl-icd=2.3.3
  - omegaconf=2.3.0
  - opencl-headers=2025.06.13
  - opencv=4.13.0
  - openexr=3.4.4
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openjph=0.26.0
  - openldap=2.6.10
  - openssl=3.6.1
  - opentelemetry-api=1.39.1
  - opentelemetry-proto=1.39.1
  - opentelemetry-sdk=1.39.1
  - opentelemetry-semantic-conventions=0.60b1
  - packaging=25.0
  - pango=1.56.4
  - pcre2=10.47
  - pillow=12.1.1
  - pip=26.0.1
  - pixman=0.46.4
  - platformdirs=4.5.1
  - pluggy=1.6.0
  - pre-commit=4.5.1
  - pretrainedmodels=0.7.4
  - propcache=0.3.1
  - protobuf=6.31.1
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulseaudio-client=17.0
  - py-opencv=4.13.0
  - pyasn1=0.6.2
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pydantic-extra-types=2.11.0
  - pydantic-settings=2.12.0
  - pygments=2.19.2
  - pyopenssl=25.3.0
  - pysocks=1.7.1
  - pytest=9.0.2
  - python=3.11.14
  - python-dotenv=1.2.1
  - python-gil=3.11.14
  - python-multipart=0.0.22
  - python_abi=3.11
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - pytorch-lightning=2.6.1
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pyyaml=6.0.3
  - qt6-main=6.10.2
  - rav1e=0.7.1
  - readline=8.3
  - requests=2.32.5
  - rich=14.3.2
  - rich-toolkit=0.19.2
  - rsa=4.9.1
  - safetensors=0.7.0
  - scikit-learn=1.8.0
  - scipy=1.17.0
  - sdl2=2.32.56
  - sdl3=3.4.0
  - segmentation-models-pytorch=0.5.0
  - setuptools=82.0.0
  - shaderc=2025.5
  - shellingham=1.5.4
  - simsimd=6.5.0
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.2
  - sniffio=1.3.1
  - spirv-tools=2026.1
  - sqlparse=0.5.5
  - starlette=0.52.1
  - stringzilla=4.6.0
  - svt-av1=4.0.0
  - sympy=1.14.0
  - tbb=2022.3.0
  - threadpoolctl=3.6.0
  - timm=1.0.24
  - tk=8.6.13
  - tomli=2.4.0
  - torchmetrics=1.8.2
  - torchtriton=3.0.0
  - torchvision=0.19.0
  - tqdm=4.67.3
  - typer=0.21.2
  - typer-slim=0.21.2
  - typer-slim-standard=0.21.2
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - ukkonen=1.1.0
  - urllib3=2.6.3
  - uvicorn=0.40.0
  - uvicorn-standard=0.40.0
  - uvloop=0.22.1
  - virtualenv=20.36.1
  - watchfiles=1.1.1
  - wayland=1.24.0
  - wayland-protocols=1.47
  - websockets=16.0
  - wheel=0.46.3
  - wrapt=2.1.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.13
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.7
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.5
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.7
  - yaml=0.2.5
  - yarl=1.22.0
  - zipp=3.23.0
  - zlib-ng=2.3.3
  - zstd=1.5.7
