early_stopping:
  monitor: ${general.scheduler_monitor}
  mode: ${general.metric_mode}
  patience: 5
  min_delta: 0.001
  verbose: True

model_checkpoint:
  filename: '{epoch}-{${general.scheduler_monitor}:.6f}'
  monitor: ${general.scheduler_monitor}
  mode: ${general.metric_mode}
  save_top_k: 1
  save_last: True

other_callbacks:
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step
  - _target_: pytorch_lightning.callbacks.RichProgressBar
    leave: True
  - _target_: pytorch_lightning.callbacks.ModelSummary
    max_depth: 1
