defaults:
  - _self_
  - labels: multiclass_broken
  - datamodule: datamodule
  - model: smp
  - loss: tversky
  - optimizer: adamw
  - scheduler: cosine_annealing
  - trainer: default
  - callbacks: callbacks
  - logger: mlflow_local

general:
  learning_rate: 3e-4
  batch_size: 20
  crops_per_image: 10
  raw_mask_px_th: 0
  scheduler_interval: epoch
  scheduler_monitor: valid_loss
  metric_mode: min
  scheduler_frequency: 1
  random_seed: 8888

  split_proportions:
    - 80
    - 10
    - 10

hydra:
  run:
    dir: training/${now:%Y-%m-%d_%H-%M-%S}
