defaults:
  - _self_
  - labels: binary_fuzzy_ball
  - datamodule: datamodule
  - model: smp_unet_effnet
  - loss: dice
  - optimizer: adamw
  - scheduler: plateau
  - trainer: test
  - callbacks: callbacks
  - logger: mlflow_local

general:
  learning_rate: 1e-4
  batch_size: 3
  scheduler_interval: epoch
  scheduler_monitor: valid_loss
  metric_mode: min
  scheduler_frequency: 1
  random_seed: 8888

hydra:
  run:
    dir: training/${now:%Y-%m-%d_%H-%M-%S}
