image_size:
  height: 256
  width: 4096

dataloaders:
  num_workers: 15

  train:
    batch_size: ${general.batch_size}
    num_workers: ${datamodule.dataloaders.num_workers}
    shuffle: True
    pin_memory: True

  valid:
    batch_size: ${general.batch_size}
    num_workers: ${datamodule.dataloaders.num_workers}
    shuffle: False
    pin_memory: True

  test:
    batch_size: ${general.batch_size}
    num_workers: ${datamodule.dataloaders.num_workers}
    shuffle: False
    pin_memory: True

